refs #5 - adding travis ci & code sniffer
vpg/disturb pull request #33
Opened 2017-11-03 12:06 UTC by mbrenguier

#5

2017-11-07 22:58 UTC, jrmbrgs requested changes
maybe it's a TEST PR, to validate the CI setup...
If not, it sounds there are too many changed file not related to the PR topic.

2017-11-07 22:58 UTC, jrmbrgs commented on Library/Services/ManagerServiceInterface.php
> + * Provides helper functions that act upon a token array and modify the file
?? :p

2017-11-07 22:58 UTC, jrmbrgs commented on Library/Services/ManagerServiceInterface.php
> + * @version  0.0.1
??

2017-11-07 22:58 UTC, jrmbrgs commented on Library/Services/ManagerServiceInterface.php
> + * @category Test
??

2017-11-07 22:58 UTC, jrmbrgs commented on Library/Services/ManagerServiceInterface.php
> + * @link     http://example.com/my/bar Documentation of Foo.
rm

2017-11-07 22:58 UTC, jrmbrgs commented on Library/Services/WorkflowManager.php
> +        if(empty($this->config->steps[$nextStepPos])) {
this has already been moved in a dedicated func..
This PR sounds not up to date

2017-11-07 22:58 UTC, jrmbrgs commented on Library/Services/WorkflowManager.php
> +    public function isNextStepRunnable(string $workflowProcessId) : bool
obsolete code, replaced by getCurrentStepStatus.
Please rebase

2017-11-08 08:38 UTC, mbrenguier commented
this PR helps me to create "test" builds

2017-11-08 14:45 UTC, closed without merging