update dtos message structure
vpg/disturb pull request #7
Opened 2017-10-06 10:30 UTC by mbrenguier

2017-10-09 08:09 UTC, jrmbrgs requested changes
Some general comments, not directly related to you PR : 
 * we should remove the ...\Dtos\... in the namespace, just \Disturb\Message, class type should not be in namespaces
 * DTO should provide a `isValid()` method
 * keep in mind to make Disturb as independent as  possible, in other words, avoid interfaces to implement or abstract classes to extends client side

2017-10-09 08:09 UTC, jrmbrgs commented on Library/Dtos/Message.php
>      public function offsetGet($offset) {
We should remove the implementation of array access, it was just here to make easier the transition between php array to DTO

2017-10-09 08:09 UTC, jrmbrgs commented on Library/Dtos/Message.php
> +    public function getPayload() {
maybe add test if non empty and add the return type to be safer

2017-10-09 08:09 UTC, jrmbrgs commented on example/Services/StepInterface.php
> +namespace Ex\Services;
whey do you redelcare the interface in the example ?
It's supposed to be provided by \Disturb, the client code should not have to re-declare it

2017-10-09 08:09 UTC, jrmbrgs commented on Library/Step/AbstractStep.php
> +abstract class AbstractStep extends \Phalcon\Mvc\User\Component
Maybe it would be less coercive to expose message returns type as const e.g. \Disturb\Message\Return::Success \Disturb\Message\Return::Failure rather than forcing client to extends the abstract class which provides "poor logic"

2017-10-13 08:42 UTC, mbrenguier commented on example/Services/StepInterface.php
> +namespace Ex\Services;
mistake

2017-10-13 09:37 UTC, jrmbrgs commented on Library/Dtos/Message.php
>      public function offsetGet($offset) {
will do it

2017-10-13 09:39 UTC, jrmbrgs requested changes

2017-10-13 09:39 UTC, jrmbrgs commented on Library/Tasks/ManagerTask.php
> +            foreach ($stepInputList as $stepJob) {
stepJobHash

2017-10-13 13:55 UTC, merged