#80 - Manage JSON/PHP workflow config file with workflowConfigDto
vpg/disturb pull request #83
Opened 2017-12-13 15:15 UTC by adefretin

2017-12-15 10:17 UTC, tpellegatta commented on Library/Workflow/WorkflowManagerInterface.php
> +     * @throws |Vpg\Disturb\Workflow\WorkflowException
Typo here

2017-12-18 09:12 UTC, tpellegatta approved these changes

2017-12-18 11:10 UTC, jrmbrgs requested changes

2017-12-18 11:10 UTC, jrmbrgs commented on Library/Core/Logger/Logger.php
>          if (defined('DISTURB_DEBUG') && DISTURB_DEBUG == true) {
exit fast
```PHP
if (!defined('DISTURB_DEBUG') || !DISTURB_DEBUG) {
    return message;
}
```

2017-12-18 11:10 UTC, jrmbrgs commented on Library/Core/Logger/Logger.php
> +            if (!empty($debugBacktraceHash[2])) {
exit fast
```php
if (empty($debugBacktraceHash[2])) {
   return message;
}
```

2017-12-18 11:10 UTC, jrmbrgs commented on Library/Workflow/ManagerWorker.php
> +        return $this->workflowConfigDto->getServicesClassNameSpace() . "\\" . ucFirst($this->workflowConfigDto->getWorkflowName()) .
Maybe it could be safer to check the Class name validity, at least by checking dto func returns or even more by checking the class exists

2017-12-18 11:10 UTC, jrmbrgs commented on bin/disturb.php
> -$console = new ConsoleApp();
mmm not sure this is good to removing these two lines ...

2017-12-18 11:10 UTC, jrmbrgs commented on bin/disturb.php
>      $console->handle($arguments);
sound this var has been removed ...
did you run a test workflow successfully w/ this code ?

2017-12-18 11:10 UTC, jrmbrgs commented on example/Full/test.php
> +<?php
it would be better to give this file a meaningful name ;)

2017-12-19 10:55 UTC, merged